In [1]:
import numpy as np

In [2]:
bs=np.random.rand(1024,1024)

In [3]:
%timeit bs@bs

8.24 ms ± 162 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
import apple

In [5]:
mul=apple.jit("[(x::M ₁₀₂₄,₁₀₂₄ float)%.(y::M ₁₀₂₄,₁₀₂₄ float)]")

In [6]:
mulT=apple.jit("[(x::M ₁₀₂₄,₁₀₂₄ float)%.|:(y::M ₁₀₂₄,₁₀₂₄ float)]")

In [7]:
mul(bs,bs)

array([[256.40450606, 252.35871495, 243.70858199, ..., 262.81777412,
        249.82292257, 249.26795285],
       [254.92488235, 253.12296265, 243.50356861, ..., 261.47076881,
        254.39551085, 252.65109496],
       [261.9745817 , 258.94638589, 251.10746666, ..., 260.82235492,
        258.63103093, 255.21244417],
       ...,
       [260.42253102, 250.8647101 , 249.44494069, ..., 262.06608462,
        254.05247507, 252.35875481],
       [264.97399754, 266.23341271, 253.6682069 , ..., 268.71002622,
        262.26714626, 254.77144973],
       [261.08450576, 258.59684457, 246.78622483, ..., 260.77020816,
        253.35510999, 257.77386786]], shape=(1024, 1024))

In [8]:
bs@bs

array([[256.40450606, 252.35871495, 243.70858199, ..., 262.81777412,
        249.82292257, 249.26795285],
       [254.92488235, 253.12296265, 243.50356861, ..., 261.47076881,
        254.39551085, 252.65109496],
       [261.9745817 , 258.94638589, 251.10746666, ..., 260.82235492,
        258.63103093, 255.21244417],
       ...,
       [260.42253102, 250.8647101 , 249.44494069, ..., 262.06608462,
        254.05247507, 252.35875481],
       [264.97399754, 266.23341271, 253.6682069 , ..., 268.71002622,
        262.26714626, 254.77144973],
       [261.08450576, 258.59684457, 246.78622483, ..., 260.77020816,
        253.35510999, 257.77386786]], shape=(1024, 1024))

In [9]:
bs@bs.T

array([[338.22093524, 247.11847475, 255.13406784, ..., 256.00685356,
        264.08121326, 249.17903412],
       [247.11847475, 339.45735356, 261.68487023, ..., 256.4798958 ,
        258.86807025, 263.9096506 ],
       [255.13406784, 261.68487023, 348.61521908, ..., 260.36098159,
        265.77052082, 259.81861568],
       ...,
       [256.00685356, 256.4798958 , 260.36098159, ..., 345.00256919,
        256.6779526 , 262.13908669],
       [264.08121326, 258.86807025, 265.77052082, ..., 256.6779526 ,
        360.43195145, 266.91263633],
       [249.17903412, 263.9096506 , 259.81861568, ..., 262.13908669,
        266.91263633, 345.77151647]], shape=(1024, 1024))

In [10]:
mulT(bs,bs)

array([[338.22093524, 247.11847475, 255.13406784, ..., 256.00685356,
        264.08121326, 249.17903412],
       [247.11847475, 339.45735356, 261.68487023, ..., 256.4798958 ,
        258.86807025, 263.9096506 ],
       [255.13406784, 261.68487023, 348.61521908, ..., 260.36098159,
        265.77052082, 259.81861568],
       ...,
       [256.00685356, 256.4798958 , 260.36098159, ..., 345.00256919,
        256.6779526 , 262.13908669],
       [264.08121326, 258.86807025, 265.77052082, ..., 256.6779526 ,
        360.43195145, 266.91263633],
       [249.17903412, 263.9096506 , 259.81861568, ..., 262.13908669,
        266.91263633, 345.77151647]], shape=(1024, 1024))

In [11]:
%timeit mul(bs,bs)

169 ms ± 1.04 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [12]:
%timeit mulT(bs,bs)

150 ms ± 499 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [13]:
%timeit bs@bs.T

8.27 ms ± 147 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
