In [1]:
import numpy as np

In [2]:
def sigmoid (x):
    return 1/(1+np.exp(-x))

In [3]:
inputs = np.array([[0.,0],[0,1],[1,0],[1,1]])

In [4]:
hidden_weights=np.array([[0.51426693,0.56885825],[0.48725347,0.15041493]])

In [5]:
hidden_bias=np.array([0.79726405,0.67601843])

In [6]:
output_weights=np.array([[0.14801747],[0.37182892]])

In [7]:
output_bias=0.57823076

In [8]:
import apple

In [9]:
code=apple.jit("λX.λwh.λbh. [1%(1+ℯ(_x))]`{0} ([(+)`bh x]'(X%.wh))")

In [10]:
hidden_layer_output=apple.f(code,inputs,hidden_weights,hidden_bias)

In [11]:
def forward(inputs,hidden_weights,hidden_bias):
    hidden_layer_activation = np.dot(inputs,hidden_weights)
    hidden_layer_activation += hidden_bias
    hidden_layer_output = sigmoid(hidden_layer_activation)
    return hidden_layer_output

In [12]:
forward(inputs,hidden_weights,hidden_bias)

array([[0.68938893, 0.66284947],
       [0.78321778, 0.69560025],
       [0.78776923, 0.77641173],
       [0.8580009 , 0.80143567]])

In [13]:
def prediction(hidden_layer_output,output_weights,output_bias):
    output_layer_activation = np.dot(hidden_layer_output,output_weights)
    output_layer_activation += output_bias
    predicted_output = sigmoid(output_layer_activation)
    return predicted_output

In [14]:
prediction(hidden_layer_output,output_weights,output_bias)

array([[0.71641322],
       [0.72167893],
       [0.72780743],
       [0.73169254]])

In [15]:
src=apple.jit("λho.λwo.λbo. [1%(1+ℯ(_x))]'((+bo)'(ho%:wo))")

In [16]:
output_weights = output_weights.reshape([2])

In [17]:
apple.f(src,hidden_layer_output,output_weights,output_bias)

array([0.71641322, 0.72167893, 0.72780743, 0.73169254])